### ISSUE TITLE
update-test-group.sh should support tag values, not only names

### ISSUE THREAD

**Issue by mcamou** [balena-io-projects/staged-releases#27]
In some use cases you might have devices with the same tag but different values. It would be useful for `update-test-group.sh` to allow for updating all devices with a tag and a value, not just all devices with a tag. See https://github.com/balena-io-projects/staged-releases/pull/26.

**Comment by mcamou** [comment]
Closing since #26 has been merged.

**Comment by thgreasi** [comment]
Thank again for your contribution on this @mcamou
